### ISSUE TITLE
Feature Request: Imbalance Detection

### ISSUE THREAD

**Issue by oransel** [gbzenobi/CSharp-NT8-OrderFlowKit#8]
I came across your work a few days ago and I would like start by thanking you for your contribution to the open source community of traders. Building up on your initial work here, I am interested in exploring the possibility to implement what is showing in the chart screenshot below.

<img width="1002" alt="Screen Shot 2022-06-27 at 9 12 50 PM" src="https://user-images.githubusercontent.com/1380693/176090983-80333b85-b25c-47b2-8c34-b6a1e370c8ee.png">

Features shown on this chart are:

- Volume Imbalance Cluster Detection
- Unfinished Auction Detection
- Volume Imbalance Detection
- Bid Volume per Price
- Bid Volume per Bar
- Ask Volume per Price
- Ask Volume per Bar
- Most Traded Price at Each Bar
- Delta per Bar
- Accumulated Delta per Bar
- Bid X Ask, Ask X Bid, Total Volume or Delta Value in Each Cell

**Comment by oransel** [comment]
@gbzenobi any thoughts in detecting stacked imbalance and styling bid/ask like above?

**Comment by gbzenobi** [comment]
> I came across your work a few days ago and I would like start by thanking you for your contribution to the open source community of traders. Building up on your initial work here, I am interested in exploring the possibility to implement what is showing in the chart screenshot below.
> 
> <img alt="Screen Shot 2022-06-27 at 9 12 50 PM" width="1002" src="https://user-images.githubusercontent.com/1380693/176090983-80333b85-b25c-47b2-8c34-b6a1e370c8ee.png">
> 
> Features shown on this chart are:
> 
>     * Volume Imbalance Cluster Detection
> 
>     * Unfinished Auction Detection
> 
>     * Volume Imbalance Detection
> 
>     * Bid Volume per Price
> 
>     * Bid Volume per Bar
> 
>     * Ask Volume per Price
> 
>     * Ask Volume per Bar
> 
>     * Most Traded Price at Each Bar
> 
>     * Delta per Bar
> 
>     * Accumulated Delta per Bar
> 
>     * Bid X Ask, Ask X Bid, Total Volume or Delta Value in Each Cell

Hello oransel right now im working in other proyects, my time now is dedicated in AI research so i let the code to people who wants do his own ideas and implementations, if you want you can do whatever modifcation you like.

By the way, UAD is the unique information my order flow dont provide, the rest is all included...

Thanks for your time.

**Comment by oransel** [comment]
> > I came across your work a few days ago and I would like start by thanking you for your contribution to the open source community of traders. Building up on your initial work here, I am interested in exploring the possibility to implement what is showing in the chart screenshot below.
> > <img alt="Screen Shot 2022-06-27 at 9 12 50 PM" width="1002" src="https://user-images.githubusercontent.com/1380693/176090983-80333b85-b25c-47b2-8c34-b6a1e370c8ee.png">
> > Features shown on this chart are:
> > ```
> > * Volume Imbalance Cluster Detection
> > 
> > * Unfinished Auction Detection
> > 
> > * Volume Imbalance Detection
> > 
> > * Bid Volume per Price
> > 
> > * Bid Volume per Bar
> > 
> > * Ask Volume per Price
> > 
> > * Ask Volume per Bar
> > 
> > * Most Traded Price at Each Bar
> > 
> > * Delta per Bar
> > 
> > * Accumulated Delta per Bar
> > 
> > * Bid X Ask, Ask X Bid, Total Volume or Delta Value in Each Cell
> > ```
> 
> Hello oransel right now im working in other proyects, my time now is dedicated in AI research so i let the code to people who wants do his own ideas and implementations, if you want you can do whatever modifcation you like.
> 
> By the way, UAD is the unique information my order flow dont provide, the rest is all included...
> 
> Thanks for your time.

Thank you for quick response. As far as I can tell, order imbalance is detected diagonally. I can't seem to find that in this library. I am missing it?

**Comment by gbzenobi** [comment]
Sorry, you are right, that characteristic is not implemented...
This library is thinked for make analysis and dump that info into a file(for example for make Machine learning). Thats the reason why the bookmap has its own DB. But in generally you can do discretional trading very good.

I let the graphs library separatly because of this, you can modify the base code and use it for automatic volume analysis.

**Comment by ipsquare** [comment]
Thank you @gbzenobi for sharing this awesome lib.

@oransel I'm interested in this feature too. Please let me know if we can collaborate for this and a few more features too.

**Comment by oransel** [comment]
@ipsquare I already coded this separately from this indicator. It doesn't visualize on the bars but only the detection part. Let me know if you need help.

**Comment by ipsquare** [comment]
@oransel should we connect on discord xxxx ?

**Comment by oransel** [comment]
@ipsquare sent you a friend request.

**Comment by asraghu123** [comment]
Can you include me too ?

**Comment by oransel** [comment]
Here is a Discord server. We can all collaborate. It is empty but we can shape it slowly.  https://discord.gg/aQUbWTRKvm

**Comment by asraghu123** [comment]
Thanks i am travelling will login over the weekend

**Comment by andreimitocaru** [comment]
@oransel i'm also interested to get into the discord, but the invitation link doesn't work anymore.

**Comment by oransel** [comment]
> @oransel i'm also interested to get into the discord, but the invitation link doesn't work anymore.

We had good collaboration in the beginning but once we accomplished what we were set to, it started stagnating, so I shut the Discord server down. I'm not using this library anymore. I have written my own.

**Comment by andreimitocaru** [comment]
Is it possible to share your new library with me?

vin., 24 feb. 2023, 17:46 Mustafa ***@***.***> a scris:

**Comment by TomCallan** [comment]
@oransel Any possibility you could share what you eventually came up with?
